
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okxoacqnfbnuuvwhwqpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9reG9hY3FuZmJudXV2d2h3cXBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3Mzg4NDMsImV4cCI6MjA1NjMxNDg0M30.Fa33DScywVtJxeCmwQwYu0H_FP8XovTrACcQr4HgCxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
